"""Install the secret-scan pre-commit hook into ``.git/hooks/``.

Use this when you don't have (or don't want) the ``pre-commit`` framework
installed. It writes a small shim into ``.git/hooks/pre-commit`` that
invokes ``scripts/pre_commit_secret_scan.py`` against staged files.

Usage
-----

    python scripts/install_git_hooks.py

Idempotent: re-running overwrites the existing file. Use ``--uninstall``
to remove the hook.

The framework alternative
-------------------------

If you already use the ``pre-commit`` framework (``pip install pre-commit``,
then ``pre-commit install``), the repo's ``.pre-commit-config.yaml``
wires the same scanner via a ``local`` hook entry. The two approaches
are equivalent in behavior; ``pre-commit`` adds nicer multi-tool
orchestration, ``install_git_hooks.py`` adds zero dependencies.
"""

from __future__ import annotations

import argparse
import os
import stat
import sys
from pathlib import Path


HOOK_BODY = """#!/bin/sh
# AUTO-GENERATED by scripts/install_git_hooks.py — do not edit by hand.
# Re-run the installer to refresh, or use the `pre-commit` framework via
# .pre-commit-config.yaml.

# Run the secret scanner on every staged text file. The scanner exits
# non-zero on findings; git will abort the commit.
#
# The scanner enumerates staged files ITSELF (--staged uses
# `git diff --cached --name-only --diff-filter=ACM -z`, NUL-separated).
# A previous version of this hook did the enumeration in shell and
# piped it through unquoted `xargs`, which word-split filenames with
# spaces/brackets — "[USER] My Deck [B3].dck" became four bogus paths
# that the scanner then skipped as missing, i.e. the file was SILENTLY
# never scanned. Keeping the file list inside Python (argv never
# transits a shell) closes that hole for every legal filename.

exec python scripts/pre_commit_secret_scan.py --staged
"""


def _hooks_dir() -> Path:
    """Return ``<repo>/.git/hooks`` for the current repo."""

    # Walk up from cwd looking for `.git`.
    cwd = Path.cwd()
    for candidate in (cwd, *cwd.parents):
        git_dir = candidate / ".git"
        if git_dir.is_dir():
            return git_dir / "hooks"
        # Worktree case: .git is a file pointing at the real gitdir.
        if git_dir.is_file():
            content = git_dir.read_text(encoding="utf-8").strip()
            if content.startswith("gitdir:"):
                real = Path(content.split(":", 1)[1].strip())
                if not real.is_absolute():
                    real = candidate / real
                return real / "hooks"
    raise SystemExit(
        "Not inside a git repository (no .git found in cwd or any parent)."
    )


def install() -> int:
    hooks = _hooks_dir()
    hooks.mkdir(parents=True, exist_ok=True)
    target = hooks / "pre-commit"
    target.write_text(HOOK_BODY, encoding="utf-8", newline="\n")
    # Make executable (no-op semantically on Windows but git for Windows
    # respects the +x bit set in the file mode for shipped hooks).
    current_mode = target.stat().st_mode
    target.chmod(current_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    print(f"Installed pre-commit hook at: {target}")
    print("Test it with:  git commit --allow-empty -m smoke")
    return 0


def uninstall() -> int:
    hooks = _hooks_dir()
    target = hooks / "pre-commit"
    if target.exists():
        target.unlink()
        print(f"Removed: {target}")
    else:
        print(f"No hook to remove: {target}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--uninstall",
        action="store_true",
        help="Remove the pre-commit hook instead of installing it.",
    )
    args = parser.parse_args(argv)

    if args.uninstall:
        return uninstall()
    return install()


if __name__ == "__main__":
    sys.exit(main())
